/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sureshjoshi.core;

public class ISeePlusPlus {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ISeePlusPlus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ISeePlusPlus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SeePlusPlus_WrapperJNI.delete_ISeePlusPlus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int Multiply(int x, int y) {
    return SeePlusPlus_WrapperJNI.ISeePlusPlus_Multiply__SWIG_0(swigCPtr, this, x, y);
  }

  public double Multiply(double x, double y) {
    return SeePlusPlus_WrapperJNI.ISeePlusPlus_Multiply__SWIG_1(swigCPtr, this, x, y);
  }

  public IntVector RandomNumbers(int size) {
    return new IntVector(SeePlusPlus_WrapperJNI.ISeePlusPlus_RandomNumbers(swigCPtr, this, size), true);
  }

  public StringVector Sort(StringVector inStrings) {
    return new StringVector(SeePlusPlus_WrapperJNI.ISeePlusPlus_Sort(swigCPtr, this, StringVector.getCPtr(inStrings), inStrings), true);
  }

}
