/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sureshjoshi.core;

public class SeePlusPlus_WrapperJNI {
  public final static native long new_IntVector__SWIG_0();
  public final static native long new_IntVector__SWIG_1(long jarg1);
  public final static native long IntVector_size(long jarg1, IntVector jarg1_);
  public final static native long IntVector_capacity(long jarg1, IntVector jarg1_);
  public final static native void IntVector_reserve(long jarg1, IntVector jarg1_, long jarg2);
  public final static native boolean IntVector_isEmpty(long jarg1, IntVector jarg1_);
  public final static native void IntVector_clear(long jarg1, IntVector jarg1_);
  public final static native void IntVector_add(long jarg1, IntVector jarg1_, int jarg2);
  public final static native int IntVector_get(long jarg1, IntVector jarg1_, int jarg2);
  public final static native void IntVector_set(long jarg1, IntVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_IntVector(long jarg1);
  public final static native long new_StringVector__SWIG_0();
  public final static native long new_StringVector__SWIG_1(long jarg1);
  public final static native long StringVector_size(long jarg1, StringVector jarg1_);
  public final static native long StringVector_capacity(long jarg1, StringVector jarg1_);
  public final static native void StringVector_reserve(long jarg1, StringVector jarg1_, long jarg2);
  public final static native boolean StringVector_isEmpty(long jarg1, StringVector jarg1_);
  public final static native void StringVector_clear(long jarg1, StringVector jarg1_);
  public final static native void StringVector_add(long jarg1, StringVector jarg1_, String jarg2);
  public final static native String StringVector_get(long jarg1, StringVector jarg1_, int jarg2);
  public final static native void StringVector_set(long jarg1, StringVector jarg1_, int jarg2, String jarg3);
  public final static native void delete_StringVector(long jarg1);
  public final static native void delete_ISeePlusPlus(long jarg1);
  public final static native int ISeePlusPlus_Multiply__SWIG_0(long jarg1, ISeePlusPlus jarg1_, int jarg2, int jarg3);
  public final static native double ISeePlusPlus_Multiply__SWIG_1(long jarg1, ISeePlusPlus jarg1_, double jarg2, double jarg3);
  public final static native long ISeePlusPlus_RandomNumbers(long jarg1, ISeePlusPlus jarg1_, int jarg2);
  public final static native long ISeePlusPlus_Sort(long jarg1, ISeePlusPlus jarg1_, long jarg2, StringVector jarg2_);
  public final static native long new_SeePlusPlus();
  public final static native void delete_SeePlusPlus(long jarg1);
  public final static native int SeePlusPlus_Multiply__SWIG_0(long jarg1, SeePlusPlus jarg1_, int jarg2, int jarg3);
  public final static native double SeePlusPlus_Multiply__SWIG_1(long jarg1, SeePlusPlus jarg1_, double jarg2, double jarg3);
  public final static native long SeePlusPlus_RandomNumbers(long jarg1, SeePlusPlus jarg1_, int jarg2);
  public final static native long SeePlusPlus_Sort(long jarg1, SeePlusPlus jarg1_, long jarg2, StringVector jarg2_);
  public final static native long SeePlusPlus_SWIGUpcast(long jarg1);
}
