/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sureshjoshi.core;

public class SeePlusPlus extends ISeePlusPlus {
  private transient long swigCPtr;

  protected SeePlusPlus(long cPtr, boolean cMemoryOwn) {
    super(SeePlusPlus_WrapperJNI.SeePlusPlus_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SeePlusPlus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SeePlusPlus_WrapperJNI.delete_SeePlusPlus(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SeePlusPlus() {
    this(SeePlusPlus_WrapperJNI.new_SeePlusPlus(), true);
  }

  public int Multiply(int x, int y) {
    return SeePlusPlus_WrapperJNI.SeePlusPlus_Multiply__SWIG_0(swigCPtr, this, x, y);
  }

  public double Multiply(double x, double y) {
    return SeePlusPlus_WrapperJNI.SeePlusPlus_Multiply__SWIG_1(swigCPtr, this, x, y);
  }

  public IntVector RandomNumbers(int size) {
    return new IntVector(SeePlusPlus_WrapperJNI.SeePlusPlus_RandomNumbers(swigCPtr, this, size), true);
  }

  public StringVector Sort(StringVector inStrings) {
    return new StringVector(SeePlusPlus_WrapperJNI.SeePlusPlus_Sort(swigCPtr, this, StringVector.getCPtr(inStrings), inStrings), true);
  }

}
